### ISSUE TITLE
Stratum issues after last update 

### ISSUE THREAD

**Issue by Beanservers** [afiniel/yiimp_install_script#14]
have problem with stratum. In stratum add mine_port, i add column mine_port in my db, but stratum giver error: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'.
How would fix this error? or how do you get into phpmyadmin to edit the sql or even miriadb 

thanks 

19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'
19:23:53: SQL ERROR: 1054, Unknown column 'mine_port' in 'field list'

**Comment by afiniel** [comment]
Add new tables in stratum: `ALTER TABLE coins ADD mine_port INT NULL AFTER specifications;` You can read more about it https://github.com/Kudaraidee/yiimp/issues/88

**Comment by Beanservers** [comment]
> Add new tables in stratum: `ALTER TABLE coins ADD mine_port INT NULL AFTER specifications;` You can read more about it [Kudaraidee/yiimp#88](https://github.com/Kudaraidee/yiimp/issues/88)

thanks is that the mysql ? thank you
