### ISSUE TITLE
ERROR : Rpc_do_call

### ISSUE THREAD

**Issue by seblezinzin** [afiniel/yiimp_install_script#22]
For Babacoin, CPU GR.

Setup ran well but in screen for coin, I'm getting this error : 
15:28:43: ERROR: rpc_do_call: localhost:6532 500
15:28:43: ERROR Babacoin Block decode failed
15:28:43: *** REJECTED :( Babacoin block 175799 1 txs

Daemon run on localhost on port 6532, rpc user and password are correct.

Any idea ?

**Comment by seblezinzin** [comment]
Live 322 on this https://github.com/Kudaraidee/yiimp/blob/dev/stratum/coinbase.cpp
add a solution, can you update your stratum ?

**Comment by afiniel** [comment]
else if (strcmp(coind->symbol, "BBC") == 0)
{
    char payees[4];
    int npayees = 1;
    char script_dests[4096] = { 0 };

    json_value* smartnode = json_get_object(json_result, "smartnode");
    debuglog("BBC DETECTED Json: RESULT %p\n", (void*)smartnode);
    bool smartnode_started = json_get_bool(json_result, "smartnode_payments_started");
    if (smartnode_started && smartnode && smartnode->type == json_array)
    {
        for (int i = 0; i < smartnode->u.array.length; i++)
        {
            const char* payee = json_get_string(smartnode->u.array.values[i], "payee");
            json_int_t amount = json_get_int(smartnode->u.array.values[i], "amount");
            if (payee && amount)
            {
                char script_payee[128] = { 0 };
                npayees++;
                available -= amount;
                base58_decode(payee, script_payee);
                job_pack_tx(coind, script_dests, amount, script_payee);
            }
            debuglog("SMARTNODE DETECTED Payee: %s\n", payee);
        }
    }

    json_value* founder = json_get_object(json_result, "founder");
    bool founder_payments_started = json_get_bool(json_result, "founder_payments_started");
    if (founder_payments_started && founder)
    {
        const char* founder_payee = json_get_string(founder, "payee");
        json_int_t founder_amount = json_get_int(founder, "amount");
        if (founder_payee && founder_amount)
        {
            char founder_script_payee[128] = { 0 };
            npayees++;
            available -= founder_amount;
            base58_decode(founder_payee, founder_script_payee);
            job_pack_tx(coind, script_dests, founder_amount, founder_script_payee);
        }
        debuglog("FOUNDER DETECTED Payee: %s\n", founder_payee);
    }

    sprintf(payees, "%02x", npayees);
    strcat(templ->coinb2, payees);
    strcat(templ->coinb2, script_dests);
    job_pack_tx(coind, templ->coinb2, available, NULL);
    strcat(templ->coinb2, "00000000"); // locktime
    if (coinbase_payload && strlen(coinbase_payload) > 0)
    {
        char coinbase_payload_size[18];
        ser_compactsize((unsigned int)(strlen(coinbase_payload) >> 1), coinbase_payload_size);
        strcat(templ->coinb2, coinbase_payload_size);
        strcat(templ->coinb2, coinbase_payload);
    }

    coind->reward = (double)available / 100000000 * coind->reward_mul;
    return;
}

**Comment by afiniel** [comment]
Maybe works?
