### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by richshibe** [afiniel/yiimp_install_script#24]
After installing I get this broken index screen, only a little bit of text. Same happens in the admin area.
![Screenshot 2023-05-31](https://github.com/afiniel/yiimp_install_script/assets/69731496/44c5693b-76af-4b79-9ca0-8e17b6b8ba08)

Tried the usual method to fix white screen of death and didn't work either. 
sudo apt install php7.3-memcached

Please help. Thank you!

**Comment by richshibe** [comment]
![image](https://github.com/afiniel/yiimp_install_script/assets/69731496/89f88766-976c-4b1c-a8d8-108fd7a6c60d)
Digging the log file , looks like it's failing to opne the DB connection . Any ideas?

**Comment by afiniel** [comment]
What yiimpool Version do you use? type: yiimpool in terminal to find out the version

**Comment by richshibe** [comment]
v0.8.8
