### ISSUE TITLE
script not working at ubuntu 18.04 ( no 7.3 php 7.4 php )

### ISSUE THREAD

**Issue by mraksoll4** [afiniel/yiimp_install_script#26]
script not working at ubuntu 18.04 ( no 7.3 php or 7.4 php )

and need choice to install or not install daemon builder , not all need that.

**Comment by afiniel** [comment]
I will add the choice to install DaemonBuilder or not

**Comment by mraksoll4** [comment]
it is fully not work ...
started in /home/crypto-data/yiimp/site/web/
exception: CDbConnection failed to open the DB connection.
