### ISSUE TITLE
ubuntu 20.04 exception: CDbConnection failed to open the DB connection.

### ISSUE THREAD

**Issue by mraksoll4** [afiniel/yiimp_install_script#30]
how fix this  at ubuntu 20.04?

Fri 08 Sep 2023 01:45:59 PM UTC
started in /home/crypto-data/yiimp/site/web/
exception: CDbConnection failed to open the DB connection.
exception: CDbConnection failed to open the DB connection.

i think it's php problem

**Comment by afiniel** [comment]
Thank for letting me know I will have a look at it when I have a computer available, but something my be wrong in the my.cnf when the script edit it, that progress should be in the db.sh file

**Comment by STV00** [comment]
The error occoured while i am using yiimp command
if php version 8.x.x or somting else is installed it cant connect to the database i think

little fix for the first error i have found by installing with this script

my ubuntu 20.04 is installing or using php 8.x.x
this is the fix i found by other yiimp repos. 


sudo apt install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt update

sudo update-alternatives --set php /usr/bin/php7.3
