### ISSUE TITLE
There is an error in the gr algorithm for skytere

### ISSUE THREAD

**Issue by Zeusyf** [afiniel/yiimp_install_script#31]
there are some people mining skytere in my pool with a power of 1.6 Mhs but it has been 2 days without getting a single block, I have checked all the settings and no errors were found

**Comment by afiniel** [comment]
You can have a look in the logs and also have a look in the screen. To do so write: 

screen -list 

so we all the screen and in this case to open the coin screen use:

screen -r skyt should it be in this case. But I believe you just have bad luck on finding blocks, reach back when you have look up the logs. 

Regards

**Comment by Zeusyf** [comment]
solved
