### ISSUE TITLE
system.sh ubuntu 20.04

### ISSUE THREAD

**Issue by KekwCoin** [afiniel/yiimp_install_script#35]
=>  Clone Yiimp Repo <=
system.sh: line 243: YiiMPRepo: unbound variable

please fix

**Comment by Canefis** [comment]
same sh@t, any fix?

**Comment by Simkas45** [comment]
![Uploading photo_2023-12-15_05-25-12.jpg…]()

**Comment by Simkas45** [comment]
![photo_2023-12-15_05-25-12](https://github.com/afiniel/yiimp_install_script/assets/43626253/52398b0d-0d36-4128-8efa-b8ab78ec79e3)

**Comment by afiniel** [comment]
Fixed
