### ISSUE TITLE
Algo list

### ISSUE THREAD

**Issue by cpuminingpool** [afiniel/yiimp_install_script#39]
algo drop down list is missing algos

**Comment by afiniel** [comment]
I need some more info

**Comment by cpuminingpool** [comment]
ones i do the full install on ubuntu 20 and im going to add a coin on the drop down algo list there are algos missing 
![Untitled](https://github.com/afiniel/yiimp_install_script/assets/107811954/9834e738-8752-4c6e-8917-40fbefb63397)
![Untitled](https://github.com/afiniel/yiimp_install_script/assets/107811954/0a7c168d-81e7-4d3b-99d7-02fe16414cbc)

**Comment by Zeusyf** [comment]
@cpuminingpool I have experienced the same problem to overcome this



Make sure your PHP version is PHP 7.3.

Check the version using the command: `php -v`

If it shows version 8.3 or any other, run the following command:

Alternative PHP Configurations:
Check the alternative PHP configurations on your system. Sometimes, you may need to set the default PHP version or enable a specific version with the following command:


**`sudo update-alternatives --config php`**
Select PHP 7.3 from the displayed list.

Update PHP Links:
After configuring the alternative PHP, update the PHP links with the command:

`sudo update-alternatives --set php /usr/bin/php7.3`
Verify PHP Version:
Run the` php -v` command again to ensure that the currently active PHP version is PHP 7.3.

Once completed and you've confirmed that version 7.3 is in use, you will see all algorithms displayed.

**Comment by cpuminingpool** [comment]
@Zeusyf  that did it thank you for the help
